GET http://localhost:8000/user HTTP/1.1

###
POST http://localhost:8000/add_user
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com"
}

###
PUT http://localhost:8000/user/3
Content-Type: application/json

{
    "name": "Updated 3",
    "email": "xx@c.zom"
}

###
DELETE url HTTP/1.1